### ISSUE TITLE
This lib breaks the build in RN 0.14.0

### ISSUE THREAD

**Issue by jforaker** [bulenttastan/react-native-list-popover#10]
On package start you will see this error and it does not run the server because of it:

```
[10:37:29 AM] <START> request:/index.android.map?platform=android
Error: Naming collision detected: 
/Users/me/JAKT/crashr_react_native/node_modules/react-native-list-popover/node_modules/react-native/packager/react-packager/src/DependencyResolver/haste/polyfills/polyfills.js 

collides with /Users/me/app/node_modules/react-native/packager/react-packager/src/DependencyResolver/polyfills/polyfills.js

```

**Comment by gs-akhan** [comment]
delete node_modules and run `npm install` again.

**Comment by httnn** [comment]
@gs-akhan that didn't work :(

**Comment by gs-akhan** [comment]
@bodyflex just try deleting 
node_modules/react-native-list-popover/node_modules/

**Comment by Ouadie** [comment]
Same error for me `Error: Naming collision detected:`, I've already tried to delete **node_modules** then **node_modules/react-native-list-popover/node_modules/**

**Comment by feelingweird** [comment]
Hi All,
just had the same issue, removed nested modules folder and i was still getting some react-native issues. I am wondering if the nested node_modules are because of `"_npmVersion": "2.1.17",` in the package.json?

**Comment by niftylettuce** [comment]
Same issue, I get a naming collision in 0.20.x:

``` log
Failed to build DependencyGraph: Naming collision detected: /Users/nexus/Public/MyProject/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/nexus/Public/MyProject/node_modules/react-native-list-popover/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
Error: Naming collision detected: /Users/nexus/Public/MyProject/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/nexus/Public/MyProject/node_modules/react-native-list-popover/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/nexus/Public/MyProject/node_modules/promise/lib/core.js:37:12)
    at /Users/nexus/Public/MyProject/node_modules/promise/lib/core.js:123:15
    at flush (/Users/nexus/Public/MyProject/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

**Comment by niftylettuce** [comment]
See #15 for a solution
